CREATE TABLE IF NOT EXISTS `NAVIGASI` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `AKRONIM` varchar(10) NOT NULL,
  `NAME` varchar(20) NOT NULL,
  `LEVEL` INT(11) NOT NULL,
  `CHILD` INT(11) NOT NULL,
  `stts_data` int(11) NOT NULL,
  `c_data` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=2 ;
